Done

diff --git a/web_server/0-transfer_file b/web_server/0-transfer_file
--- a/web_server/0-transfer_file
+++ b/web_server/0-transfer_file
@@ -1,10 +1,15 @@
 #!/usr/bin/env bash
 # Transfers a file from our client to a server
 #
-# variables
 if [ $# -lt 4 ]
 then
-  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
 else
-  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
+  echo "Transferring file..."
+  scp -v -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
+  if [ $? -eq 0 ]; then
+    echo "File transfer successful."
+  else
+    echo "File transfer failed."
+  fi
 fi
